services:
  server:
    build: ./server
    restart: always
    ports:
      - '5020:5020'
    environment:
      - PORT=5020
      - NZ_TAB_URL=https://json.tab.co.nz/schedule/
      - MONGODB_URI=mongodb://host.docker.internal:27017/raceday2

    networks:
      - app-network

  client:
    build: ./client
    restart: always
    ports:
      - '3020:3020'
    environment:
      - API_URL=http://server:5020
      - NEXT_PUBLIC_API_URL=http://localhost:5020

    networks:
      - app-network

    depends_on:
      - server

networks:
  app-network:
    driver: bridge
